#!/bin/bash

export PYTHONPATH=$(pwd)
RELEASE_DIR=release

if [[ -d release ]]
then
    lsof | grep release/dist/run_athena/.nfs | awk '{print$2}'| xargs kill -9
    rm -rf release
fi

mkdir -vp $RELEASE_DIR

cd $RELEASE_DIR

pyinstaller ../main/run_athena.py --hidden-import sklearn.neighbors.typedefs \
                --hidden-import sklearn.neighbors.quad_tree \
                --hidden-import sklearn.tree._utils \
                --hidden-import scipy._lib.messagestream \
                --hidden-import packaging \
                --hidden-import six.moves.html_parser \
                --hidden-import multiprocessing.util \
                --hidden-import packaging.specifiers


#cp -rfv ../config .

ln -sf ../config .
ln -sf ../scripts .

cd dist/run_athena
ln -sf ../../build/run_athena/TA_Lib-0.4.17-py2.7-linux-x86_64.egg/talib .
